[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "daphne your_project.asgi:application --port $PORT --bind 0.0.0.0"
healthcheckPath = "/"
restartPolicyType = "on_failure"